import type { Metadata } from "next";
import { DockComponent } from "@/components/app-with-dock";
import Navbar from "@/components/Navbar";
import { DialogProvider } from "@/components/contexts/useDialogContext";
import { SpendProvider } from "@/components/contexts/useSpendContext";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SpendProvider>
        <DialogProvider>
        <div className="flex flex-col max-w-lg mx-auto h-dvh overflow-hidden">
            <Navbar />
            <div className="flex-1">{children}</div>
            <DockComponent />
        </div>
        </DialogProvider>
        </SpendProvider>

    );
}
